name: WebdriverIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ORANGEHRM 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred Node.js version

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Install dependencies
        run: npm install

      - name: Check environment variables
        run: |
          echo "Username is set: $([[ -n "$ORANGEHRM_USERNAME" ]] && echo 'YES' || echo 'NO')"
          echo "Password is set: $([[ -n "$ORANGEHRM_PASSWORD" ]] && echo 'YES' || echo 'NO')"
        env:
          ORANGEHRM_USERNAME: ${{ secrets.ORANGEHRM_USERNAME }}
          ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}

      - name: Run WebdriverIO tests
        env:
          ORANGEHRM_USERNAME: ${{ secrets.ORANGEHRM_USERNAME }}
          ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}
        run: npm test